version: 2.1
orbs:
  node: circleci/node@1.1.6
  jira: circleci/jira@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            post-steps:
              - jira/notify
