version: 2.1
orbs:
  node: circleci/node@1.1.6
  jira: circleci/jira@1.1.6

executors:
  node:
    parameters:
      image:
        type: string
        default: "13"
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  restore_checkout_code: &restore_checkout_code
    restore_cache:
      name: Restore checkout code
      keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  restore_modules: &restore_modules
    restore_cache:
      name: Restore Npm Package Cache
      key: dependency-cache-{{ checksum "package-lock.json" }}

  restore_storybook: &restore_storybook
    restore_cache:
      name: Restore storybook cache
      key: v1-storybook-dist-{{ .Environment.CIRCLE_BRANCH }}-{{
        .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/filter-search-circleci

  install:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - <<: *restore_checkout_code
      - <<: *restore_modules
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build_storybook:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - <<: *restore_checkout_code
      - <<: *restore_modules
      - run:
          name: Build storybook
          command: npm run build-storybook
      - save_cache:
          key: v1-storybook-dist-{{ .Environment.CIRCLE_BRANCH }}-{{
            .Environment.CIRCLE_SHA1 }}
          paths:
            - storybook-static

  deploy_dev:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - <<: *restore_checkout_code
      - <<: *restore_storybook
      - run:
          name: Install Netlify CLI
          command: sudo npm install netlify-cli -g
      - run:
          name: Netlify Deploy
          command: npm run storybook-deploy-dev

  test:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - <<: *restore_checkout_code
      - <<: *restore_modules
      - run: npm test


  lint:
    executor: node
    working_directory: ~/filter-search-circleci
    steps:
      - <<: *restore_checkout_code
      - <<: *restore_modules
      - run: npm test

workflows:
  version: 2
  testing-linting:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
          post-steps:
            - jira/notify
      - lint:
          requires:
            - install
          post-steps:
            - jira/notify
      - test:
          requires:
            - install
          post-steps:
            - jira/notify
      - build_storybook:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - develop
                - master
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: unmapped
      - deploy_dev:
          requires:
            - build_storybook
          filters:
            branches:
              only:
                - develop
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: development


